name: run shiny_action

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04

    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v3

    # install the python version needed, install packages 
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10.10'
            cache: 'pip'
      - run: pip install -r requirements.txt
    
      # create pull requrest on specific branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Build shiny
          committer: CptQuak <kamilkulesza5@gmail.com>
          body: |
            Build shiny app
          title: '[Update] shiny'
          labels: shiny, automated pr
          assignees: CptQuak
          reviewers: CptQuak
          branch: action_shiny