name: run shiny_action

on:
    workflow_dispatch:
    push:
    
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04

    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v3

    # install the python version needed, install packages 
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10.10'
            cache: 'pip'
      - run: pip install -r requirements.txt
    
    # shiny site
      - name: build static files
        run: shinylive export app docs

      - uses: actions/checkout@v3
      - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Build shiny app"
            git push
